# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview4-011223'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: docker build -t vehiclesui .
  displayName: 'docker build'         
  
- script: docker tag vehiclesui altenchallengecontainers.azurecr.io/vehiclesui:v1
  displayName: 'docker tag'  
  
- script: docker login https://altenchallengecontainers.azurecr.io -u AltenChallengeContainers -p SIgnOHm5+EWnoupFU5TC77GZOfiUBHkS
  displayName: 'docker login'
  
- script: docker push altenchallengecontainers.azurecr.io/vehiclesui:v1
  displayName: 'docker push'